"""new fields in user model

Revision ID: 10069146b158
Revises: cc394e5eab72
Create Date: 2019-12-11 20:48:21.973984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10069146b158'
down_revision = 'cc394e5eab72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
